config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'
  
  resources :homes do
    collection do
      get 'search'
      get 'about'
    end
  end
  resources :events
  resources :daily_reports do
    resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :daily_report
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
    has_many :comments
    belongs_to :user

    validates :date, presence: true
    validates :tire, presence: true, if: :scrim?
    validates :decide, presence: true, if: :scrim?
    validates :winround, presence: true, if: :scrim?
    validates :loseround, presence: true, if: :scrim?

  def scrim?
    title == "スクリム"
  end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user

    validates :title, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :daily_reports
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :teamname, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @daily_report = DailyReport.find(params[:daily_report_id])
        @comment = Comment.new(comment_params)

        if @comment.save!
        redirect_back(fallback_location: root_path)
        else
        redirect_back(fallback_location: root_path)
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            redirect_back(fallback_location: root_path)       
        else
            redirect_back(fallback_location: root_path)       
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:comment_content, :daily_report_id, :comment_name) 
    end
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :rate_calc, only: [:show]
  def index
    @daily_reports = current_user.daily_reports.page(params[:page]).per(10).order(date: 'DESC')

    current_user.rate =  1000 + current_user.daily_reports.pluck(:rate).compact.sum
    current_user.save

    @chart = current_user.daily_reports.group(:date).sum(:rate)
  end

  def new
    @daily_report = DailyReport.new
  end

  def edit
  end

  def show
    @comment = Comment.new
    @comments = @daily_report.comments
  end

 def create
  @daily_report = DailyReport.new(report_params)
   @daily_report.user_id = current_user.id
   if @daily_report.save!
    redirect_to @daily_report
   else
    render 'new'
   end
 end

 def update
  if @daily_report.update(report_params)
    redirect_to @daily_report
  else
    render 'edit'
  end
 end

 def destroy
   if @daily_report.destroy
    redirect_to daily_reports_path
   else
    render 'edit'
   end
 end

 private

 def set_report
  @daily_report = DailyReport.find(params[:id])
end

def report_params
  params.require(:daily_report).permit(:title, :team, :body, :date, :username, :winround, :loseround, :tire, :decide)
end

def rate_calc
    if @daily_report.decide == 'win'
    @daily_report.rate = (((@daily_report.winround - @daily_report.loseround)* 10) +100)+(1 / @daily_report.tire * 50)
    elsif @daily_report.decide == 'lose'
      @daily_report.rate = (((@daily_report.loseround - @daily_report.winround)* -10)-100)-(1 / @daily_report.tire * 50)
    else
    @daily_report.rate = 0
    end
  @daily_report.save
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  def index
    @events = current_user.events.all
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def show
  end

 def create
   @event = Event.new(event_params)
   @event.user_id = current_user.id
   if @event.save
    redirect_to events_path
   else
    render 'new'
   end
 end

 def update
  if @event.update(event_params)
    redirect_to events_path
  else
    render 'edit'
  end
 end

 def destroy
   if @event.destroy
    redirect_to events_path
   else
    render 'edit'
   end
 end

 private

 def set_event
  @event = Event.find(params[:id])
end

def event_params
  params.require(:event).permit(:title, :body, :start_date, :end_date, :user_id)
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/daily_reports/edit.html.erb
<div class ='container'>
<%=form_for (@daily_report) do |f| %>
    <label>投稿者</label>
    <div class = 'form-group pb-3'>
        <%= f.text_field :username, class: 'form-control'%>
    </div>

    <hr>

    <div class = 'row py-3'>
        <div class = 'col-md-5 text-center'>
            <div class ='form-group'>
            <select name="daily_report[title]" id="daily_report_title" onchange="func(this);">
                <option value="">選択して下さい</option>
                <option value="スクリム">スクリム</option>
                <option value="研究">研究</option>
                <option value="その他">その他</option>
            </select>
                <%#= f.select :title, [['スクリム', 'スクリム'], ['研究', '研究'], ['その他', 'その他']], include_blank: "選択して下さい", class: 'form-control', onchange: 'func(this);'%>
            </div>
        </div>

        <div class = 'col-md-4 mx-auto'>
            <div class ='form-group'>
                <%= f.date_field :date, class: 'form-control w-50'%>
            </div>
        </div>
    </div>
    <div id = 'scrim'>
        <div class ='row'>
            <div class ='col-md-3 form-inline text-center'>
                対戦相手Tire：<%= f.number_field :tire, class: 'form-control w-25', min: 1, max: 4%>
            </div>

            <div class = 'col-md-6'>
                <div class ='form-inline'>
                    獲得ラウンド：
                    <!- input class="form-control w-25" min="0" max="12" value="0" type="number" name="daily_report[winround]" id="daily_report_winround" onchange= "decider(this);" ->
                    <%= f.number_field :winround, class: 'form-control w-25', min: 0, max: 12, onchange: 'decider(this);'%>
                     vs 
                    <!- input class="form-control w-25" min="0" max="12" value="0" type="number" name="daily_report[loseround]" id="daily_report_loseround" onchange= "decider(this); -">
                    <%= f.number_field :loseround, class: 'form-control w-25', min: 0, max: 12, onchange: 'decider(this);'%>
                    ：敗北ラウンド
                </div>
            </div>

            <div class = 'col-md-3 text-center'>
                <div class ='btn-group btn-group-toggle' data-toggle = 'buttons'>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'win', id: 'win_button'%>Win
                    </label>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'lose', id: 'lose_button'%>Lose
                    </label>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'drow', id: 'drow_button'%>Drow
                    </label>
                </div>
            </div>
        </div>
    </div>
    <hr>

        
        <label>活動内容・反省等</label>
        <%= f.hidden_field :body, id: :daily_report_body, class: 'form-control'%>
        <trix-editor rows = '10', input="daily_report_body"></trix-editor>
        <%= f.submit '更新', class: 'form-control mt-3 btn btn-primary'%>
    </div>
<%end%>
</div>

<script language="javascript" type="text/javascript">
    document.getElementById('scrim').style.display = "none";
    var title = document.getElementById('daily_report_title');
    function func(){
        if(title.value == "スクリム"){
            document.getElementById('scrim').style.display = "";
        }else if (title.value != "スクリム"){
            document.getElementById('scrim').style.display = "none";
        }
    }

    var win = document.getElementById('daily_report_winround');
    var lose = document.getElementById('daily_report_loseround');
    function decider(){
        var win = document.getElementById('daily_report_winround');
        var lose = document.getElementById('daily_report_loseround');
        var winbutton = document.getElementById('win_button');
        var losebutton = document.getElementById('lose_button');
        var drowbutton = document.getElementById('drow_button');
            if(Number(win.value) > Number(lose.value)){
                winbutton.click();
                winbutton.checked = true;
            }else if (Number(win.value) < Number(lose.value)){
                losebutton.click();
                losebutton.checked = true;
            }else if(Number(win.value) == Number(lose.value)){
                drowbutton.click();
                drowbutton.checked = true;
            }
        }
</script>

app/views/daily_reports/index.html.erb
<div class ='container'>
<%= link_to '新規作成', new_daily_report_path, class: 'btn btn-success my-3 form-control' %>

    <table class="table">
    <tr>
    <th>タイトル</th>
    <th>日付</th>
    <th>投稿者</th>
    <th>スコア</th>
    <th></th>
    </tr>
    <% @daily_reports.each do |daily|%>
                <tr>
                  <td><%= daily.title%></td>
                  <td><%= daily.date%></td>
                  <td><%= daily.username%></td>
                  <td><%= daily.rate.to_i%></td>
                  <td><%= link_to '詳細', daily_report_path(daily.id)%></td>
                </tr>
    <%end%>
    </table>
    <%= paginate @daily_reports, theme: 'twitter-bootstrap-4', class: '' %>
</div>
</div>

<%#= line_chart @chart %>

app/views/daily_reports/new.html.erb
<div class ='container'>
<%=form_for (@daily_report) do |f| %>
    <label>投稿者</label>
    <div class = 'form-group pb-3'>
        <%= f.text_field :username, class: 'form-control'%>
    </div>

    <hr>

    <div class = 'row py-3'>
        <div class = 'col-md-5 text-center'>
            <div class ='form-group'>
            <select name="daily_report[title]" id="daily_report_title" onchange="func(this);">
                <option value="">選択して下さい</option>
                <option value="スクリム">スクリム</option>
                <option value="研究">研究</option>
                <option value="その他">その他</option>
            </select>
                <%#= f.select :title, [['スクリム', 'スクリム'], ['研究', '研究'], ['その他', 'その他']], include_blank: "選択して下さい", class: 'form-control', onchange: 'func(this);'%>
            </div>
        </div>

        <div class = 'col-md-4 mx-auto'>
            <div class ='form-group'>
                <%= f.date_field :date, value: Time.now.strftime("%Y-%m-%d"), class: 'form-control w-50'%>
            </div>
        </div>
    </div>
    <div id = 'scrim'>
        <div class ='row'>
            <div class ='col-md-3 form-inline text-center'>
                対戦相手Tire：<%= f.number_field :tire, class: 'form-control w-25', min: 1, max: 4, value: 4%>
            </div>

            <div class = 'col-md-6'>
                <div class ='form-inline'>
                    獲得ラウンド：
                    <%= f.number_field :winround, class: 'form-control w-25', min: 0, max: 12, value: 0, onchange: 'decider(this);'%>
                     vs 
                    <%= f.number_field :loseround, class: 'form-control w-25', min: 0, max: 12, value: 0, onchange: 'decider(this);'%>
                    ：敗北ラウンド
                </div>
            </div>
            
            <div class = 'col-md-3 text-center'>
                <div class ='btn-group btn-group-toggle' data-toggle = 'buttons'>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'win', id: 'win_button'%>Win
                    </label>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'lose', id: 'lose_button'%>Lose
                    </label>
                    <label class ='btn btn-outline-secondary'>
                        <%= f.radio_button :decide, 'drow', id: 'drow_button'%>Drow
                    </label>
                </div>
            </div>

        </div>
    </div>
    <hr>

        
        <label>活動内容・反省等</label>
        <%= f.hidden_field :body, id: :daily_report_body, class: 'form-control'%>
        <trix-editor rows = '10', input="daily_report_body"></trix-editor>
        <%= f.submit '登録', class: 'form-control mt-3 btn btn-primary'%>
    </div>
<%end%>
</div>

<script language="javascript" type="text/javascript">
    document.getElementById('scrim').style.display = "none";
    var title = document.getElementById('daily_report_title');
    function func(){
        if(title.value == "スクリム"){
            document.getElementById('scrim').style.display = "";
        }else if (title.value != "スクリム"){
            document.getElementById('scrim').style.display = "none";
        }
    }

    function decider(){
        var win = document.getElementById('daily_report_winround');
        var lose = document.getElementById('daily_report_loseround');
        var winbutton = document.getElementById('win_button');
        var losebutton = document.getElementById('lose_button');
        var drowbutton = document.getElementById('drow_button');
            if(Number(win.value) > Number(lose.value)){
                winbutton.click();
                winbutton.checked = true;
            }else if (Number(win.value) < Number(lose.value)){
                losebutton.click();
                losebutton.checked = true;
            }else if(Number(win.value) == Number(lose.value)){
                drowbutton.click();
                drowbutton.checked = true;
            }
        }
</script>

app/views/daily_reports/show.html.erb
<div class ='container'>
<div class ='border p-3 mb-3'>
    <ul class =''>
        <li class ='mt-3'>投稿者:　<%= @daily_report.username%></li>
        <li class ='mt-3'>タイトル:　<%= @daily_report.title%></li>
        <%if @daily_report.title == 'スクリム'%>
        <%= @daily_report.winround%> vs <%= @daily_report.loseround%> [<%= @daily_report.decide%>]
        <li class = 'mt-3'>スコア：　<%= @daily_report.rate.to_i %></li>
        <%end%>
        <li class ='mt-3'>日付:　　　<%= @daily_report.date%></li>
        <li class ='mt-3'>内容:</li>
        <div class ='mt-2'><%= sanitize @daily_report.body %></div>

    </ul>

</div>

<%= link_to '削除', daily_report_path, method: :delete, class: 'btn btn-danger float-right'%>
<%= link_to '編集', edit_daily_report_path, class: 'btn btn-secondary float-right mr-3'%>



<%= form_for [@daily_report, @comment] do |c| %>
    <div class ="form-group pt-5">
        <label>名前：</label>
        <%= c.text_field :comment_name, class: 'form-control col-3 mb-2'%>
        <label>コメント：</label>
        <%= c.text_field :comment_content, class: 'form-control pr-5' %>
        <%= c.hidden_field :daily_report_id, value:@daily_report.id %>
        <%= c.submit "コメント送信", class:'btn btn-success float-right mt-3 mb-3'%>
    </div>
<% end %>

<table class="table">
    <thead>
        <tr>
        <th>送信者</th>
        <th>コメント</th>
        <th>　　</th>
        </tr>
    </thead>


    <% @comments.each do |comment| %>
        <tr>
        <td><%= comment.comment_name%></td>
        <td><%= comment.comment_content%></td>
        <td><%= link_to "削除", daily_report_comment_path(@daily_report, comment), method: :delete%></td>
        </tr>
    <% end %>
</table>
</div>

app/views/events/edit.html.erb
<div class ='container'>
<%=form_for (@event) do |f| %>
    <div class = 'form-group'>
    <label>タイトル：</label>
    <%= f.text_field :title, class: 'form-control mb-2'%>
    <label>詳細：</label>
    <%= f.text_area :body, class: 'form-control'%>
    </div>

    <div class ='form-inline'>
    <label>期限：</label>
    <%= f.date_field :start_date, class: 'form-control mr-2'%>~<%= f.date_field :end_date, class: 'form-control ml-2'%>
    </div>
    <%= f.submit '更新', class: 'form-control mt-3 btn btn-primary'%>
<%end%>
</div>

app/views/events/index.html.erb
<div class ='container'>
<%= link_to '新規作成', new_event_path, class: 'btn btn-success my-4 form-control'%>

<div id="calendar" class = "col-8 mx-auto"></div>

    <table class="table">
    <tr>
    <th>開始日</th>
    <th>終了日</th>
    <th>タイトル</th>
    <th></th>
    </tr>
<% @events.each do |event| %>
    <tr>
    <td><%= event.start_date.strftime('%-m月%-d日(%a)') %></td>
    <td><%= event.end_date.strftime('%-m月%-d日(%a)') %></td>
    <td><%= event.title %></td>
    <td><%= link_to '詳細', event_path(event.id)%></td>
    </tr>
<% end %>
</table>
</div>

app/views/events/new.html.erb
<div class ='container'>
<%=form_for (@event) do |f| %>
    <div class = 'form-group'>
    <label>タイトル：</label>
    <%= f.text_field :title, class: 'form-control mb-2'%>
    <label>詳細：</label>
    <%= f.text_area :body, class: 'form-control'%>
    </div>

    <div class ='form-inline'>
    <label>期限：</label>
    <%= f.date_field :start_date, class: 'form-control mr-2'%>~<%= f.date_field :end_date, class: 'form-control ml-2'%>
    </div>
    <%= f.submit '登録', class: 'form-control mt-3 btn btn-primary'%>
<%end%>
</div>

app/views/events/show.html.erb
<div class ='container'>
<div class ='border p-3 mb-3'>
    <ul class =''>
        <li class ='mt-3'>開始日:　<%= @event.start_date%></li>
        <li class ='mt-3'>終了日:　<%= @event.end_date%></li>
        <li class ='mt-3'>タイトル:　<%= @event.title%></li>
        <li class ='mt-3'>詳細:　<%= @event.body%></li>
    </ul>
</div>

<%= link_to '削除', event_path, method: :delete, class: 'btn btn-danger float-right'%>
<%= link_to '編集', edit_event_path, class: 'btn btn-secondary float-right mr-3'%>
</div>

app/views/homes/_logined.html.erb
<%#= line_chart current_user.pluck(:rate, :date), xmin: Time.current.prev_month, xmax: Time.current %>

<div class="jumbotron" style="">
  <h1 class ="text-center display-3">
    <%= current_user.teamname %>
  </h1>
  <hr>
  <h1 class ="text-center display-2">
    <%= current_user.rate.to_i %>
  </h1>
  <hr>
  <h1 class ="text-center display-4">
  予想Tire：
  <% if (0..1500).include? current_user.rate%>
  4
  <% elsif (1501..2000).include? current_user.rate %>
  3
  <% elsif (2001..2500).include? current_user.rate %>
  2
  <% elsif (2501..99999).include? current_user.rate %>
  1
  <% end %>
  </h1>
</div>

<div class = 'container'>
<%= link_to '活動を記録する', daily_reports_path, class: 'btn btn-success form-control mb-3'%>

</div>

app/views/homes/_nologin.html.erb
<div class ='nologin'>
<div class="jumbotron jumbotron-fluid container-fluid" style ='height: 600px'>
 <div class ='box1'>
  <h1 class="display-1 text-white text-center mb-5">Sixer</h1>
  <h4 class="text-white text-center"><strong>Rainbow Six Siege アマ・プロチームのために考えられた、チームマネジメントサービス</strong></h4>
  <br>
  <h3 class="text-white text-center"><strong>----- スクリムレートランキング首位を目指せ -----</strong></h4>
  <hr class="my-4">
  <div class = 'text-right mr-3'>
  <p class = 'text-white'>アカウント作成、ログインは下のボタンから↓</p>
    <%= link_to 'サインアップ', new_user_registration_path, class: 'btn btn-success px-5' %>
    <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary px-5' %>
    </div>
    </div>
</div>
</div>

app/views/homes/index.html.erb
<% if user_signed_in? %>
  <%= render 'logined'%>
<% else %>
  <%= render 'nologin'%>
<% end %>

<footer class ="bg-dark">
    <div class ="container">
      <div class ="col-md-6 mx-auto text-white pb-5 pt-3 mt-3">
        <li>
          お問い合わせはTwitterのDMまで
        <a href = "https://twitter.com/mkrms_s" class="fab fa-twitter-square fa-3x text-white float-right"></a>
        </li>
      </div>
        <p class ="text-center text-white my-0">Niiyama keisuke</p>
    </div>
</footer>

app/views/homes/search.html.erb
<table class = 'table container'>
<tr>
    <th>順位</th>
    <th>チーム名</th>
    <th>レート</th>
</tr>
<% User.page(params[:page]).per(20).order(rate: 'DESC').each.with_index(1) do |team, i| %>
<tr>
    <td>
    <%= i%>
    </td>
    <td>
    <%= team.teamname%>
    </td>
    <td>
    <%= team.rate.to_i%>
    </td>
</tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Report</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbolinks='false'>
    <nav class="navbar navbar-dark bg-dark sticky-top mb-3">
      <a href="/" class="navbar-brand">Sixer</a>
      <% if user_signed_in? %>
      <div class ='navbar navber-nav ml-auto mr-3'>
        <%= link_to 'ランキング', search_homes_path, class: 'nav-item text-light px-3'%>
        <%= link_to 'カレンダー', events_path, class: 'nav-item text-light px-3'%>
        <%= link_to 'レポート', daily_reports_path, class: 'nav-item text-light px-3'%>
        <a href='/' class='nav-item text-light px-3'>Top</a>
      </div>
      <%end%>

      <div class='float-right'>
        <div class="dropdown dropleft">
        <button type="button" id="dropdown1"
      class="btn btn-secondary dropdown-toggle"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false">
      menu
      </button>
          <div class="dropdown-menu">
          <% if user_signed_in? %>
              <a href='/' class='dropdown-item'>Top</a>
              <%= link_to 'ランキング', search_homes_path, class: 'dropdown-item'%>
              <%= link_to 'カレンダー', events_path, class: 'dropdown-item'%>
              <%= link_to 'レポート', daily_reports_path, class: 'dropdown-item'%>
            <%= link_to 'プロフィール変更', edit_user_registration_path, class: 'dropdown-item'%>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item'%>
          <% else %>
              <%= link_to 'サインアップ', new_user_registration_path, class: 'dropdown-item' %>
              <%= link_to 'ログイン', new_user_session_path, class: 'dropdown-item' %>
          <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>